export const details = {
	Name: String,
	SortingName: String,
	Platform: String,
	Developers: Array,
	Publishers: Array,
	Categories: Array,
	Genres: Array,
	Features: Array,
	Tags: Array,
    Collections: Array,
	Description: String,
	ReleaseDate: Date,
	Series: String,
	AgeRating: Number,
	Region: String,
	Source: String,
	CompletionStatus: String,
	UserScore: Number,
	CriticScore: Number,
	CommunityScore: Number,
};
